export const CREATE_BINDING_POPIN_IDENTIFIER = 'create-binding-popin'
export const CREATE_CATEGORY_POPIN_IDENTIFIER = 'create-category-popin'
export const EDIT_BINDING_POPIN_IDENTIFIER = 'edit-binding-popin'
export const EDIT_CATEGORY_POPIN_IDENTIFIER = 'edit-category-popin'
export const DELETE_CONFIRMATION_POPIN_IDENTIFIER = 'delete-confirmation-popin'
